---
# tasks file for dotnetapp
- name: Create directory in /tmp
  ansible.builtin.file:
    path: /tmp/deplopyment/
    state: directory

- name: Fetch application source code on target machine
  ansible.builtin.git:
    repo: 'https://github.com/m-j/notes-app-dotnet.git'
    dest: /tmp/deplopyment
    version: 0.0.7

- name: Create directory in /opt
  ansible.builtin.file:
    path: /opt/deplopyment
    state: directory

- name: Deploy the app to target directory
  ansible.builtin.command:
    cmd: dotnet publish NotesAppDotnet/NotesAppDotnet.sln --configuration Release --output /opt/deplopyment
    chdir: /tmp/deplopyment/

- name: Create directory for SQL Database
  ansible.builtin.file:
    path: /opt/app_db
    state: directory

- name: Copy appsettings.json to target machine
  ansible.builtin.copy:
    src: appsettings.json
    dest: /opt/deplopyment/appsettings.json

- name: Copy systemd service file
  ansible.builtin.copy:
   src: dotnetapp.service
   dest: /etc/systemd/system/dotnetapp.service

- name: Reload systemd deamon
  ansible.builtin.systemd_service:
    daemon_reload: true


- name: Run application as a service
  ansible.builtin.systemd_service:
    name: dotnetapp
    state: started
    enabled: true






