---
- name: Update packages cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install dotnet-8-sdk package
  become: true
  ansible.builtin.apt:
    name: dotnet-sdk-8.0
